export default {
    Traditional: {},
    Simplified: {
        "🛠️ 調整菜單": "🛠️ 调整菜单",
        "✂️ 斷開增幅": "✂️ 断开增幅",
        "🔗 恢復增幅": "🔗 恢复增幅",
        "❌ 禁用網域": "❌ 禁用网域",
        "✅ 啟用網域": "✅ 启用网域",
        "增強錯誤": "增强错误",
        "音量增強器": "音量增强器",
        "增強倍數 ": "增强倍数 ",
        " 倍": " 倍",
        "增益": "增益",
        "頻率": "频率",
        "Q值": "Q值",
        "低頻設定": "低频设置",
        "中頻設定": "中频设置",
        "高頻設定": "高频设置",
        "動態壓縮": "动态压缩",
        "壓縮率": "压缩率",
        "過渡反應": "过渡反应",
        "閾值": "阈值",
        "起音速度": "起音速度",
        "釋放速度": "释放速度",
        "關閉": "关闭",
        "保存": "保存",
        "不支援的媒體跳過": "不支持的媒体跳过",
        "不支援音頻增強節點": "不支持音频增强节点",
        "添加增強節點成功": "添加增强节点成功",
        "添加增強節點失敗": "添加增强节点失败",
        "當前沒有被增幅的媒體": "当前没有被增幅的媒体",
        "快捷組合 : (Alt + B)": "快捷组合 : (Alt + B)"
    },
    English: {
        "🛠️ 調整菜單": "🛠️ Settings Menu",
        "✂️ 斷開增幅": "✂️ Disconnect Amplification",
        "🔗 恢復增幅": "🔗 Restore Amplification",
        "❌ 禁用網域": "❌ Disable Domain",
        "✅ 啟用網域": "✅ Enable Domain",
        "增強錯誤": "Enhancement Error",
        "音量增強器": "Volume Booster",
        "增強倍數 ": "Enhancement Multiplier ",
        " 倍": "x",
        "增益": "Gain",
        "頻率": "Frequency",
        "Q值": "Q Factor",
        "低頻設定": "Low Frequency Settings",
        "中頻設定": "Mid Frequency Settings",
        "高頻設定": "High Frequency Settings",
        "動態壓縮": "Dynamic Compressor",
        "壓縮率": "Compression Ratio",
        "過渡反應": "Knee",
        "閾值": "Threshold",
        "起音速度": "Attack",
        "釋放速度": "Release",
        "關閉": "Close",
        "保存": "Save",
        "不支援的媒體跳過": "Unsupported Media Skipped",
        "不支援音頻增強節點": "Audio Enhancement Node Not Supported",
        "添加增強節點成功": "Enhancement Node Added Successfully",
        "添加增強節點失敗": "Failed to Add Enhancement Node",
        "當前沒有被增幅的媒體": "No media is currently being amplified",
        "快捷組合 : (Alt + B)": "Shortcut: (Alt + B)"
    }

};